SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5

# Powerup Constants
POWERUP_RADIUS = 15
POWERUP_COLOR = "green"
POWERUP_SPAWN_RATE = 10.0  # seconds between powerup spawns
POWERUP_SPEED = 100  # Pixels per second

# Powerup Effect Constants
SHOT_COOLDOWN_POWERUP = 0.05
SHOT_RADIUS_POWERUP = SHOT_RADIUS * 2
SHOT_COLOR_POWERUP = "yellow"
POWERUP_DURATION = 8.0  # seconds